<a href="https://colab.research.google.com/github/ufrpe-eagri-ic/aulas/blob/master/12_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modulo Numpy
***

Numpy (http://www.numpy.org/) é um módulo fundamental para trabalhar com a computação científica em Python. Este módulo fornece um array multidimensional e diversas ferramentas para trabalhar com estes arrays. Entre as características do módulo Numpy, estão:

* Objeto de array multidimensional;
* Ferramentas de álgebra linear;
* Ferramentas de Transformada de Fourier;
* Ferramentas de geração de números aleatórios.

Para utilizar o módulo Numpy, basta importá-lo. Neste notebook, o Numpy será importado sempre da seguinte maneira:

```py
import numpy
```

Array é uma sequência de elementos do mesmo tipo, formando um conjunto n-dimensional. A forma do array pode ser visualizada através da função shape(), que retorna uma tupla com o tamanho do array em cada dimensão. Os arrays podem ser inicializados com listas e seus elementos podem ser acessados com colchetes.

Um array com uma dimensão tem somente um colchete [] com duas dimensões dois colchetes [[], []] e por ai vai.

Consulta: https://docs.scipy.org/doc/numpy/reference/

Instalação:

```
pip install numpy
```

***

# SciPy

O SciPy (https://scipy.org/) é um módulo de algoritmos e ferramentas matemáticas feito para trabalhar com os array do Numpy em Python. Algumas as principais funções do SciPy é trabalhar com:

* Álgebra Linear;
* Estatística;
* Problemas de Otimização;
* Operações com Matrizes Esparsas;
* Processamento de Sinais.

***
### Exemplos
***

In [0]:
# Importa o modulo numpy
import numpy

***

In [5]:
# Criar uma lista
my_list = [1, 2, 3]
print(my_list)

[1, 2, 3]


***

In [6]:
# Vamo através do numpy criar um array unidimensional usando a lista
array = numpy.array(my_list)
print(array)

[1 2 3]


***

In [7]:
# Visualizando a forma do array
print(array.shape)

(3,)


***

In [8]:
# Visualizando o tipo de dados do array
# No caso é um array de interios de 64 bits
print(array.dtype)

int64


***

In [9]:
# Acessando elementos individuais do array
print(array[0], array[1], array[2])

1 2 3


***

In [10]:
# Modificando o valor de um elemento do array
array[1] = 10
print(array)

[ 1 10  3]


***

In [11]:
# Pegar o maior e o menor valor e indice do array
print("Maior valor:", array.max(), "está no indice", array.argmax())
print("Menor valor:", array.min(), "está no indice", array.argmin())

Maior valor: 10 está no indice 1
Menor valor: 1 está no indice 0


***

In [12]:
# Vamo criar uma matriz utilizando várias listas
matrix = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


***

In [13]:
# Visualizando a forma da matriz
print(matrix.shape)

(3, 3)


In [14]:
# Visualizando o número de elmentos da matriz/array
matrix.size          

9

***

In [15]:
# Visualizando o tipo de dados da matriz
# No caso é uma matriz de floats de 64 bits
print(matrix.dtype)

int64


***

In [16]:
# Acessando elementos individuais da matriz
print(matrix[0][0], matrix[1][1], matrix[2][2])
print(matrix[0, 0], matrix[1, 1], matrix[2, 2])

1 5 9
1 5 9


# Métodos para ARRAYS

In [18]:
# média
arr = numpy.array([[1., 2., 3.,], [4., 5., 6.]]) 
arr.mean()

3.5

In [19]:
# definindo o axis
arr.mean(axis=0)  # colunas


array([2.5, 3.5, 4.5])

In [22]:
arr.mean(axis=1)  # linhas


array([2., 5.])

Você pode encontrar o mínimo e o máximo de um array com os métodos min e max. Às vezes é útil encontrar os índices desses mínimos e máximos. Para isso use argmin e argmax, como

In [0]:
x = np.random.rand(10)
imax = x.argmax()
print(imax, x[imax], x.max())

Há também várias maneiras de gerar sequências de números.

  - np.arange ([start,] stop [[, stride]]) Cria uma sequência de números, semelhante ao intervalo
  - np.linspace (min, max, length) Cria uma série uniforme de comprimento especificado entre min e max, inclusive.
  - np.logspace (minpow, maxpow, length) Cria uma série uniforme no espaço de logs de tamanho especificado entre 10 ** minpow e 10 ** maxpow, inclusive.

In [25]:
import numpy as np
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

TypeError: ignored

## Criação de arrays padrão

In [0]:
]:
o = np.ones((3, 4, 5))    # The argument is a shape, so is a tuple with the length of each dimension as an argument
b = np.ones((2, 3), dtype=np.bool)
z = np.zeros((2, 3), dtype=np.float32)
