<a href="https://colab.research.google.com/github/ufrpe-ensino/ic-aulas/blob/master/aulas/12_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Modulo Numpy
***

Numpy (http://www.numpy.org/) é um módulo fundamental para trabalhar com a computação científica em Python. Este módulo fornece um array multidimensional e diversas ferramentas para trabalhar com estes arrays. Entre as características do módulo Numpy, estão:

* Objeto de array multidimensional;
* Ferramentas de álgebra linear;
* Ferramentas de Transformada de Fourier;
* Ferramentas de geração de números aleatórios.

Para utilizar o módulo Numpy, basta importá-lo. Neste notebook, o Numpy será importado sempre da seguinte maneira:

```py
import numpy
```

Array é uma sequência de elementos do mesmo tipo, formando um conjunto n-dimensional. A forma do array pode ser visualizada através da função shape(), que retorna uma tupla com o tamanho do array em cada dimensão. Os arrays podem ser inicializados com listas e seus elementos podem ser acessados com colchetes.

Um array com uma dimensão tem somente um colchete [] com duas dimensões dois colchetes [[], []] e por ai vai.

Consulta: https://docs.scipy.org/doc/numpy/reference/

Instalação:

```
pip install numpy
```

***

# SciPy

O SciPy (https://scipy.org/) é um módulo de algoritmos e ferramentas matemáticas feito para trabalhar com os array do Numpy em Python. Algumas as principais funções do SciPy é trabalhar com:

* Álgebra Linear;
* Estatística;
* Problemas de Otimização;
* Operações com Matrizes Esparsas;
* Processamento de Sinais.

***
### Exemplos
***

In [1]:
# Importa o modulo numpy
import numpy

Normalmente, utilizamos um apelido para bibliotecas muito usadas, usando o modificador `as`

In [18]:
import numpy as np

***

In [20]:
# Criar uma lista
my_list = [1, 2, 3]
print(my_list)

[1, 2, 3]


***

In [19]:
# Vamos através do numpy criar um array unidimensional usando a lista
array = np.array(my_list)
print(array)

[1 2 3]


***

In [21]:
# Visualizando a forma do array
print(array.shape)

(3,)


***

In [22]:
# Visualizando o tipo de dados do array
# No caso é um array de interios de 64 bits
print(array.dtype)

int64


***

In [23]:
# Acessando elementos individuais do array
print(array[0], array[1], array[2])

1 2 3


***

In [24]:
# Modificando o valor de um elemento do array
array[1] = 10
print(array)

[ 1 10  3]


***

In [25]:
# Pegar o maior e o menor valor e indice do array
print("Maior valor:", array.max(), "está no indice", array.argmax())
print("Menor valor:", array.min(), "está no indice", array.argmin())

Maior valor: 10 está no indice 1
Menor valor: 1 está no indice 0


***

In [26]:
# Vamo criar uma matriz utilizando várias listas
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


***

In [27]:
# Visualizando a forma da matriz
print(matrix.shape)

(3, 3)


In [28]:
# Visualizando o número de elmentos da matriz/array
matrix.size          

9

***

In [12]:
# Visualizando o tipo de dados da matriz
# No caso é uma matriz de floats de 64 bits
print(matrix.dtype)

int64


***

In [29]:
# Acessando elementos individuais da matriz
print(matrix[0][0], matrix[1][1], matrix[2][2])
print(matrix[0, 0], matrix[1, 1], matrix[2, 2])

1 5 9
1 5 9


# Métodos para ARRAYS

In [30]:
# média
arr = np.array([[1., 2., 3.,], [4., 5., 6.]]) 
arr.mean()

3.5

In [31]:
# definindo o axis
arr.mean(axis=0)  # colunas


array([2.5, 3.5, 4.5])

In [32]:
arr.mean(axis=1)  # linhas

array([2., 5.])

## Criando arrays de números aleatórios

In [35]:
# cria um array com 10 numeros aleatorios (entre 0 e 1)
x = np.random.rand(10)
print(x)

[0.3816571  0.58881142 0.58758362 0.14273446 0.81270227 0.0607756
 0.62287711 0.35414181 0.59686317 0.92846691]


Você pode encontrar o mínimo e o máximo de um array com os métodos min e max. Às vezes é útil encontrar os índices desses mínimos e máximos. Para isso use argmin e argmax, como

In [37]:
imax = x.argmax()
print(imax, x[imax], x.max())

3 0.9222592159938129 0.9222592159938129


## Criando arrays com intervalos pré-determinados

Há também várias maneiras de gerar sequências de números.

  - np.arange ([start,] stop [[, stride]]) Cria uma sequência de números, semelhante ao intervalo
  - np.linspace (min, max, length) Cria uma série uniforme de comprimento especificado entre min e max, inclusive.
  - np.logspace (minpow, maxpow, length) Cria uma série uniforme no espaço de logs de tamanho especificado entre 10 ** minpow e 10 ** maxpow, inclusive.

In [38]:
import numpy as np
np.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [41]:
np.linspace(0, 1, 10) 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [42]:
np.logspace(0, 1, 10) 

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

## Criação de arrays padrão

In [44]:
o = np.ones(4)    
print(o)

[1. 1. 1. 1.]


In [46]:
# matriz 3x4 de 1´s
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [49]:
# matriz 2x3 de bool
b = np.ones((2, 3), dtype=bool)
print(b)

[[ True  True  True]
 [ True  True  True]]


In [51]:
# matriz 2x3 de 0´s
z = np.zeros((2, 3), dtype=np.float32)
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]
